# Site settings
title: Shir Ya Khat
title_fa: "شیر یا خط"
email: info@shiryakhat.net
# url: https://shiryakhat.net
url: 127.0.0.1
description: "The main goal is to remove the language barrier in order to allow the knowledge on blockchain and decentralization to be accessible to Farsi speakers, and offer a global open platform for people to discuss related subjects. "
keywords: "Bitcoin, podcast, blockchain, decentralization, farsi, iran, persian, فارسی, بیتکوین, بلاکچین, غیرمتمرکز, چیست, اتریم, رمزارز"
skills: "Persian Blockchain Podcast"
skill_fa: "پادکست آموزشی بلاکچین"
meta_author: Eskandari Shayan

# Google webmaster tools
google_verify:
google_analytics: UA-96473903-1
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 050b3e #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: efae22 #FD6E8A
  secondary-dark: ff941f #A2122F

# Footer settings
footer:
  copyright: Shir Ya Khat <br> شیر یا خط
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/shiryakhat
  # - title: facebook
  #   url:
  - title: telegram
    url: https://t.me/shiryakhatpod
  - title: soundcloud
    url: https://soundcloud.com/shiryakhat
  - title: apple
    url: https://podcasts.apple.com/us/podcast/id1221206951
  - title: google
    url: https://podcasts.google.com/?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy8xMWFhODUzYy9wb2RjYXN0L3Jzcw%3D%3D
  - title: spotify
    url: https://open.spotify.com/show/7AQ3C6yGz4haADinqtP63N?si=Y8r2AC0EStGLEDK7-RjQ7A
  - title: github
    url: http://github.com/shiryakhat


    # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'Shir Ya Khat Podcast has been made possible by volunteer work of a decentral team from United States, Canada, Germany, Netherland, South Korea, Iran, Armenia, and many more. Thank You for all your support'
# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "img"
    values:
      image: true